carbon_aware_best_time:
  name: Carbon aware best time
  description: Calculates the optimal start time (carbon aware) using 15-min Energy-Charts data. Returns immediately.
  fields:
    dataStartAt:
      name: Window start
      description: ISO 8601 with timezone (e.g., 2025-10-17T08:00:00+02:00)
      required: true
      selector:
        datetime:
    dataEndAt:
      name: Window end
      description: ISO 8601 with timezone
      required: true
      selector:
        datetime:
    expectedRuntime:
      name: Runtime (minutes)
      required: true
      default: 60
      selector:
        number:
          min: 1
          max: 1440
          mode: box
    allowedHours:
      name: Allowed hours (local)
      description: e.g., 8-21
      required: false
      selector:
        text: